In [4]:
import pandas as pd
import numpy as np
import math
from sklearn.metrics.pairwise import cosine_similarity
result = pd.read_csv("C:\\Users\\THE TAM\\Desktop\\data.csv")
#chuyen Dataframe sang Numpy
m_u = result.values[:,:]

print("---------------------------------------------------------------------------------------------------------------")

# tính sim(u,u')
def cal_each_sim(M,i,j):
    N=M.copy()   
    t=0
    m=0
    tong=0
    tich_a=0
    tich_b=0
    for k in range(0,M.shape[1]): 
        if( (pd.isnull(M[i,k])==False) and (pd.isnull(M[j,k])==False) ):
            a=float(M[i,k])
            b=float(M[j,k])
            #TINH TU SO
            tong+=(M[i,k]*M[j,k])
            # TINH MAU SO
            tich_a+= a**2
            tich_b+= b**2
    M=pd.DataFrame(M).dropna(axis=1)
    t=tong
    m = np.sqrt(tich_a*tich_b);
    return t/m
# gán sim(u,u') vào ma trận user, item
def cal_sum_sim(M):
    Sim = np.zeros((M.shape[0],M.shape[0]))
    for i in range(0,M.shape[0]):
        for j in range (0,M.shape[0]):
            if(i==j):
                Sim[i,j]=1;
            else:
                Sim[i,j]=cal_each_sim(M,i,j);
    return Sim;
# tìm K láng giềng
# y tuong: sắp xếp Sim(u,u') tăng dần, sau đó lấy hai giá trị Sim cao nhất, không lấy giá trị 1 ( vì đó là Sim(u,u) luôn =1 )
def findK(C,m,K,sort_m):
    value=0
    u_ner = np.zeros(K)
    for k in range(1,K+1):
        value = sort_m[m,C.shape[1]-k-1]
        for u_phay in range(0,C.shape[1]):
            if(value == C[m,u_phay]):
                u_ner[k-1]=u_phay
                break       
    return u_ner
# Ma tran du doan
def predic_M(M,K):
    cosin = cal_sum_sim(M)
    #print(cosin)
    sort_m = np.sort(cosin)
    for u in range(0,M.shape[0]):
        u_ner = findK(cosin,u,K,sort_m)
        for i in range(0,M.shape[1]):
            
            if(pd.isnull(M[u,i])==True):
                tu=0
                mau=0
                for j in range(K):
                    a=int(u_ner[j])
                    tu+= (cosin[u,a]) * (M[a,i])
                    mau+=(cosin[u,a])
                M[u,i] = tu/mau  
                #print(M[u,i])
    return M


print("---MA TRAN BAN DAU-----")
print(m_u)
m=m_u.copy()
print("-----------SIM USER------------")
print(cal_sum_sim(m))
print("---MA TRAN USER DU DOAN-----")
for i in range(10):
    m = predic_M(m,2)
    m=np.around(m)
print(m)       
print("----------------------------------------------------------------------------------")
print("----MA TRẬN ITEM BAN ĐẦU")
#Cách làm như ma trận user, chỉ cần chuyển vị ma trận ban đầu (ma trận d) thì ta sẽ có ma trận theo item
#Ma trận item
m_i = m_u.T
n = m_i.copy()
print(n)
print("-----------SIM ITEM------------")
print(cal_sum_sim(n))
print("---MA TRAN ITEM DU DOAN-----")
for i in range(2):
    n = predic_M(m_i,2)
    n=np.around(n)
print(n)

                         

               
    
            
    

        
        
    
    


    

---------------------------------------------------------------------------------------------------------------
---MA TRAN BAN DAU-----
[[ 1.  4.  5. nan  3.]
 [ 5.  1. nan  5.  2.]
 [ 4.  1.  2.  5. nan]
 [nan  3.  4. nan  4.]]
-----------SIM USER------------
[[1.         0.53708616 0.60609153 0.97179743]
 [0.53708616 1.         0.99391238 0.98386991]
 [0.60609153 0.99391238 1.         0.98386991]
 [0.97179743 0.98386991 0.98386991 1.        ]]
---MA TRAN USER DU DOAN-----
[[1. 4. 5. 5. 3.]
 [5. 1. 3. 5. 2.]
 [4. 1. 2. 5. 3.]
 [5. 3. 4. 5. 4.]]
----------------------------------------------------------------------------------
----MA TRẬN ITEM BAN ĐẦU
[[ 1.  5.  4. nan]
 [ 4.  1.  1.  3.]
 [ 5. nan  2.  4.]
 [nan  5.  5. nan]
 [ 3.  2. nan  4.]]
-----------SIM ITEM------------
[[1.         0.47280543 0.58549055 0.99388373 0.70710678]
 [0.47280543 1.         0.99399909 1.         0.94686415]
 [0.58549055 0.99399909 1.         1.         0.96827732]
 [0.99388373 1.         1.         1. 